### ISSUE TITLE
About RPM and its weights

### ISSUE THREAD

**Issue by herok97** [RenYang-home/PLVC#3]
Dear Author,
Thank you for your valuable work.

I am trying to reproduce your work.
I have already run RAE and generated decoded frames by commenting out RPM commands in RLVC.py, as RPM weights are not provided, to the best of my knowledge.
However, it seems that while binary files for the I+1 frame and I-1 frame are generated, binary files for other P-frames are not.
I realized that RPM should be run separately to generate binary files for other P-frames.

Could you provide the weights for RPM? or,
Unlike RLVC, didn't PLVC use RPM for all P-frames, not just the first P-frame?

Thanks again.

**Comment by RenYang-home** [comment]
Thanks for your interest in our work. The RPM weights of RLVC can be re-used for PLVC as well. Since re-training RPM on PLVC gets negligibly little improvement, we just re-use those of RLVC to PLVC.

**Comment by herok97** [comment]
Thank you very much your very very quick reply.
I will try it with the weights in RLVC !!
